name: Auto Minify Code

on:
  push:
    branches:
      - main

permissions:
  contents: write  # For auto-commit
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}  # Prevent overlapping runs

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Minify files
        uses: anthonyftwang/minify-action@v1.0.1
        with:
          directory: '.'
          overwrite: true

      - name: Auto commit minified files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto minified files"
