name: Auto Minify Code

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Minify files
        uses: nizarmah/auto-minify@v3
        with:
          directory: '.'
          overwrite: true
          filetypes: '*.html,*.css,*.js'

      - name: Auto commit minified files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto minified files"
