name: Deploy Preview

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write  # For deployment auth

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Minify files
        uses: nizarmah/auto-minify@v3
        with:
          directory: '.'
          overwrite: true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages-preview-${{ github.head_ref }} # Unique preview branch
          folder: .
